service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::lesson5-bucket"
    - Effect: "Allow"
      Action: "s3:*"
      Resource: 
        - "arn:aws:s3:::lesson5-bucket/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource: 
        - Fn::GetAtt: [ SQSQueue, Arn ]

  environment:
    SQS_URL:
      Ref: SQSQueue

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: parsed-products-queue
  Outputs:
    



functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              queryStrings:
                name: true
  parseProductsFile:
    handler: handler.parseProductsFile
    events:
      - s3:
          bucket: lesson5-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
